"""followers

Revision ID: 537e90c643d4
Revises: f9c4cc8c26b1
Create Date: 2018-07-18 16:15:12.347134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '537e90c643d4'
down_revision = 'f9c4cc8c26b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
